name: build_and_deploy
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #   - name: Docker login
      #     run: docker login ghcr.io -u $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}

      #   - name: Build nikodemwrona.dev Docker image
      #     run: |
      #       docker build --tag "ghcr.io/nikodem-wrona/nikodemwrona.dev/nikodemwrona.dev:latest" -f website/Dockerfile .

      #   - name: Push nikodemwrona.dev Docker image
      #     run: |
      #       docker push "ghcr.io/nikodem-wrona/nikodemwrona.dev/nikodemwrona.dev:latest"

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment/nikodemwrona-dev -n website
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
